version: "3.7"
services:
  db_dev:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5448:5432
    volumes:
      - db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_PORT=${DB_PORT}

volumes:
  db_dev:
