version: "3.7"
services:
  bot_solana:
    build:
      context: .
    restart: always
    ports:
      - 5777:5777
    volumes:
      - .:/src
    env_file:
      - .env
    networks:
      - bot_sol_net

networks:
  bot_sol_net:
    external: true
